# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On merge to master

# The workflow could also be triggered on PRs
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  update-signature:
    name: Update module signature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/update-signature@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_enterprise_releases_url: ${{ secrets.NEXUS_ENTERPRISE_RELEASES_URL }}

  build:
    name: Build Module
    needs: update-signature
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:8-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: jahia/jahia-modules-action/build@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          module_id: content-security-policy
          
  sbom:
    name: SBOM processing
    needs: build
    runs-on: ubuntu-latest
    container:
      image: cyclonedx/cyclonedx-cli:0.24.2   
    steps:
      - uses: jahia/jahia-modules-action/sbom-processing@v2
        with:
          dependencytrack_hostname: ${{ vars.DEPENDENCYTRACK_HOSTNAME }}
          dependencytrack_apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          sbom_artifacts: 'build-artifacts'

  integration-tests-standalone:
    uses:  Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    needs: build
    secrets: inherit
    with:
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: content-security-policy
      testrail_project: Content Security Policy
      pagerduty_skip_notification: true
      provisioning_manifest: provisioning-manifest-build.yml
      should_use_build_artifacts: true
      pagerduty_incident_service: content-security-policy-JahiaSN
      artifact_prefix: csp
      module_branch: ${{ github.head_ref }}

  publish:
    name: Publish module
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:8-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/publish@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}